default_platform :ios

platform :ios do
  before_all do
    ipa scheme: 'Buildkite Fastlane Demo'
  end

  desc "Runs all the tests"
  lane :test do
    xctest scheme: 'Buildkite Fastlane Demo',
           sdk: 'iphonesimulator',
           destination: 'platform=iOS Simulator,name=iPhone 6s,OS=9.3',
           derivedDataPath: './fastlane/xcodebuild-data'
  end
end
